name: Build and Push Packages

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo pacman -Syyu --noconfirm python expect git
      
    - name: Setting builder user
      run: |
        sudo useradd builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
        sudo chmod -R a+rw .
        sudo chown -R builder .

    - uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
        
    - name: Build and sign packages
      run: |
        echo $PACKAGE_SIGNING_PASSPHRASE
        export PASSPHRASE="ciao"
        python -c "import os;print(os.getenv('PASSPHRASE'))"
        python -c "import os;print(os.getenv('HOME'))"
        sudo -E -u builder python -c "import os;print(os.getenv('PASSPHRASE'))"
        sudo -u builder python -c "import os;print(os.getenv('HOME'))"
        sudo -u builder python build_and_sign_packages.py

    - name: Push packages to another repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git clone https://github.com/Athena-OS/athena-repository-dev.git
        cd athena-repository-dev
        cp -rf ../*.pkg.tar.zst* ./x86_64/
        cp -rf ../*.pkg.tar.zst* ./aarch64/
        ./update-database.sh
        git add --all
        git commit -m "Add built packages"
        git push https://D3vil0p3r:${{ secrets.DESTINATION_REPO_TOKEN }}@github.com/Athena-OS/athena-repository-dev.git main
