name: Build and Push Packages

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setting builder user
      run: |
        sudo useradd builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
        sudo chmod -R a+rw .
        sudo chown -R builder .

    - name: Build and sign packages
      run: |
        echo "PASSPHRASE=${{ secrets.PACKAGE_SIGNING_PASSPHRASE }}" >> $GITHUB_ENV
        echo "WE=1" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $WE
        echo $PASSPHRASE
        echo $GITHUB_ENV
